### PR TITLE
Add and Remove functionality added.

### PR DESCRIPTION
**Pull request by DilsherB**
Add and Remove functionality added.

### CODE REVIEW

**Comment by huseyinbiyik** [comment]
Hi @DilsherB, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Alt Text

## Invalid Code Review Request

❗️You have submitted a project, that has missing section on Readme file: License. Please add license section to your Readme file. Here is the link for you [Microverse Readme template](https://github.com/microverseinc/readme-template)

-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, 
👌"Add logo to navigation bar"
👌"Fix close button functionality on mobile navbar"
❌ "Added logo to navigation bar"
❌ "Added HTML"

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by DilsherB** [comment]
> Hi @DilsherB,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> Alt Text [ Alt Text ](https://camo.githubusercontent.com/999c41ff216bced575a5c7873c1c4ed04ef945c867ca87788003794670ee5aa7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f785550476377453343556b586c766f6e75672f67697068792e676966) [ ](https://camo.githubusercontent.com/999c41ff216bced575a5c7873c1c4ed04ef945c867ca87788003794670ee5aa7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f785550476377453343556b586c766f6e75672f67697068792e676966)
> ## Invalid Code Review Request
> 
> ❗️You have submitted a project, that has missing section on Readme file: License. Please add license section to your Readme file. Here is the link for you [Microverse Readme template](https://github.com/microverseinc/readme-template)
> 
>     * Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example,
>       👌"Add logo to navigation bar"
>       👌"Fix close button functionality on mobile navbar"
>       ❌ "Added logo to navigation bar"
>       ❌ "Added HTML"
> 
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

@huseyinbiyik thanks for your good review. I have updated my readme but in the next review and could not add it here. please see other functions and allow me to submit.

**Review by Qoosim — COMMENTED** [review]
#  *Status: Invalid Request* :red_circle: 

Hi @DilsherB, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 

- [ ] has some missing heading in the README file. Kindly arrange your readme file properly and add their appropriate information under each heading.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by DilsherB** [comment]
@Qoosim you can see the same project has been approved at final stage because I have updated readme with other functions. please let me submit it also.

**Pull request merged**
